config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :bookmarks

      resources :users

      resources :neighborhoods

      resources :venues

      resources :cuisines

      resources :dishes
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  ActiveAdmin.routes(self)
  root to: "dishes#index"
  resources :bookmarks
  resources :users
  resources :neighborhoods
  resources :venues
  resources :cuisines
  resources :dishes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cuisine.rb
class Cuisine < ApplicationRecord
  # Direct associations

  has_many   :dishes,
             dependent: :destroy

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    name
  end
end

app/controllers/api/v1/cuisines_controller.rb
class Api::V1::CuisinesController < Api::V1::GraphitiController
  def index
    cuisines = CuisineResource.all(params)
    respond_with(cuisines)
  end

  def show
    cuisine = CuisineResource.find(params)
    respond_with(cuisine)
  end

  def create
    cuisine = CuisineResource.build(params)

    if cuisine.save
      render jsonapi: cuisine, status: :created
    else
      render jsonapi_errors: cuisine
    end
  end

  def update
    cuisine = CuisineResource.find(params)

    if cuisine.update_attributes
      render jsonapi: cuisine
    else
      render jsonapi_errors: cuisine
    end
  end

  def destroy
    cuisine = CuisineResource.find(params)

    if cuisine.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: cuisine
    end
  end
end

app/controllers/cuisines_controller.rb
class CuisinesController < ApplicationController
  before_action :set_cuisine, only: %i[show edit update destroy]

  def index
    @q = Cuisine.ransack(params[:q])
    @cuisines = @q.result(distinct: true).includes(:dishes).page(params[:page]).per(10)
  end

  def show
    @dish = Dish.new
  end

  def new
    @cuisine = Cuisine.new
  end

  def edit; end

  def create
    @cuisine = Cuisine.new(cuisine_params)

    if @cuisine.save
      redirect_to @cuisine, notice: "Cuisine was successfully created."
    else
      render :new
    end
  end

  def update
    if @cuisine.update(cuisine_params)
      redirect_to @cuisine, notice: "Cuisine was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @cuisine.destroy
    redirect_to cuisines_url, notice: "Cuisine was successfully destroyed."
  end

  private

  def set_cuisine
    @cuisine = Cuisine.find(params[:id])
  end

  def cuisine_params
    params.require(:cuisine).permit(:name)
  end
end

app/views/cuisines/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Cuisine #<%= cuisine.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= cuisine.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back cuisine, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_cuisine_url(cuisine), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to cuisine, method: :delete, data: { confirm: "Do you really want to delete this cuisine?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(cuisine.updated_at) %> ago
  </div>
</div>

app/views/cuisines/_cuisine_dishes.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Dishes

    <a data-toggle="collapse" href="#cuisine_dishes_new_form">
      Add dish
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @cuisine.dishes.each do |dish| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to dish, dish %>

        <%= link_to dish, method: :delete, data: { confirm: "Do you really want to delete this dish" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="cuisine_dishes_new_form">
        <%= render partial: "cuisines/cuisine_dishes_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/cuisines/_cuisine_dishes_new_form.html.erb
<%= form_with(model: @dish, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <%= f.hidden_field :cuisine_id, value: @cuisine.id %>

  <div class="form-group">
    <%= f.label :notes %>
    <%= f.text_area :notes, rows: "3", class: "form-control" %>
  </div>

  <%= f.submit "Create dish", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/cuisines/_cuisines_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "cuisines_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :dishes_name_cont, "Dishes name contains" %>
    <%= f.text_field :dishes_name_cont, :class => "form-control", :placeholder => "Dishes name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/cuisines" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#cuisines_filters">
  Show filters
</a>

app/views/cuisines/_form.html.erb
<% was_validated = cuisine.errors.any? %>

<%= form_with(model: cuisine, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = cuisine.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% cuisine.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/cuisines/_list_item.html.erb
<%= link_to cuisine, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= cuisine %>
    <small class="text-muted">
      <%= time_ago_in_words(cuisine.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/cuisines/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Cuisine #<%= @cuisine.id %>
      </h2>

      <div class="card-body">
        <%= render "form", cuisine: @cuisine %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cuisines/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Cuisines

      <%= link_to new_cuisine_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "cuisines/cuisines_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Cuisines

        <%= link_to new_cuisine_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @cuisines, partial: "list_item", as: :cuisine %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @cuisines, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/cuisines/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Cuisine
      </h2>

      <div class="card-body">
        <%= render "form", cuisine: @cuisine %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/cuisines/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @cuisine, partial: "card", as: :cuisine %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "cuisines/cuisine_dishes" %>
  </div>
</div>